# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formazione', '0017_auto_20161018_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsobase',
            name='ultima_notifica_pendenza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima notifica pendenza'),
        ),
    ]
